# Generated by Django 3.0.4 on 2020-05-01 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listening',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='listening date')),
                ('extent', models.CharField(choices=[('B', 'Barely'), ('P', 'Partial'), ('C', 'Complete')], default='B', max_length=1)),
                ('vinyl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Vinyl')),
            ],
        ),
    ]
