# Generated by Django 3.0.4 on 2020-05-02 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_listening'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listening',
            options={'ordering': ['-date']},
        ),
    ]
