# Generated by Django 3.0.4 on 2020-05-09 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_vinyl_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vinyl',
            old_name='r_date',
            new_name='release_Date',
        ),
    ]
